port module InteropPorts exposing (decodeFlags, fromElm, toElm)

{-| This file was generated by elm-ts-interop init. You can manually edit this file,
just avoid exposing the low-level ports to ensure that only the FromElm and ToElm types
can be sent/received by your ports.

@docs fromElm, toElm, decodeFlags 

-}

import InteropDefinitions
import Json.Decode
import Json.Encode
import TsJson.Decode as TsDecode
import TsJson.Encode as TsEncode

{-| -}
fromElm : InteropDefinitions.FromElm -> Cmd msg
fromElm value =
    value
        |> (InteropDefinitions.interop.fromElm |> TsEncode.encoder)
        |> interopFromElm


{-| -}
toElm : Sub (Result Json.Decode.Error InteropDefinitions.ToElm)
toElm =
    (InteropDefinitions.interop.toElm |> TsDecode.decoder)
        |> Json.Decode.decodeValue
        |> interopToElm


{-| -}
decodeFlags : Json.Decode.Value -> Result Json.Decode.Error InteropDefinitions.Flags
decodeFlags flags =
    Json.Decode.decodeValue
        (InteropDefinitions.interop.flags |> TsDecode.decoder)
        flags

-- internals - do not expose

port interopFromElm : Json.Encode.Value -> Cmd msg


port interopToElm : (Json.Decode.Value -> msg) -> Sub msg